# Generated by Django 3.0.8 on 2020-08-06 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0118_product_ushop'),
        ('product', '0120_auto_20200714_0539'),
    ]

    operations = [
    ]
