# Generated by Django 3.1 on 2020-08-18 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0121_merge_20200806_1909'),
        ('product', '0121_auto_20200810_1415'),
    ]

    operations = [
    ]
