# Generated by Django 3.1 on 2020-09-17 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0123_product_ushop'),
        ('product', '0124_auto_20200909_0904'),
    ]

    operations = [
    ]
