# Generated by Django 3.1 on 2020-10-08 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0125_merge_20200917_1401'),
        ('product', '0127_auto_20201001_0933'),
    ]

    operations = [
    ]
