# Generated by Django 3.1 on 2020-10-12 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0129_auto_20201012_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='available_for_purchase',
            field=models.DateField(blank=True, null=True),
        ),
    ]
