# Generated by Django 3.1.1 on 2021-02-01 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0131_auto_20201012_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='usale',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='was_price',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
    ]
