# Generated by Django 3.1 on 2020-08-28 07:05

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import draftjs_sanitizer
import saleor.core.db.fields
import versatileimagefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0122_merge_20200818_1700'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publication_date', models.DateField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=False)),
                ('seo_title', models.CharField(blank=True, max_length=70, null=True, validators=[django.core.validators.MaxLengthValidator(70)])),
                ('seo_description', models.CharField(blank=True, max_length=300, null=True, validators=[django.core.validators.MaxLengthValidator(300)])),
                ('name', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('logo_image', versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='unurshop-shop')),
                ('logo_image_alt', models.CharField(blank=True, max_length=128)),
                ('description', models.TextField(blank=True)),
                ('description_json', saleor.core.db.fields.SanitizedJSONField(blank=True, default=dict, sanitizer=draftjs_sanitizer.clean_draft_js)),
                ('rank', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('rating_main', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('rating_uk_shipping', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('rating_product_quality', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('rating_product_price', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('rating_shuurhai', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('rating_product_rank', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('has_shipping_tax', models.BooleanField(blank=True, default=False, null=True)),
                ('shipping_per_product', models.BooleanField(blank=True, default=False, null=True)),
                ('open_graph', models.BooleanField(blank=True, default=False, null=True)),
                ('autofill', models.BooleanField(blank=True, default=True, null=True)),
                ('xero_id', models.CharField(blank=True, default=0, max_length=100, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('listSelection', models.TextField(blank=True, null=True)),
                ('productSelection', models.TextField(blank=True, null=True)),
                ('shipping_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipping_product', to='product.product')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
