# Generated by Django 3.1 on 2020-08-28 07:05

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import saleor.unurshop.package


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0047_auto_20200810_1415'),
        ('order', '0090_auto_20200824_1354'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BaraaNershil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('galig', models.CharField(max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GaduurPackage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publication_date', models.DateField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=False)),
                ('name', models.TextField(max_length=20, unique=True)),
                ('shipping_type', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('total_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('actual_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('total_paid_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('total_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('tracking_number', models.TextField(blank=True, max_length=50, null=True)),
                ('package_count', models.IntegerField(blank=True, null=True)),
                ('received_count', models.IntegerField(blank=True, null=True)),
                ('hot_count', models.IntegerField(blank=True, null=True)),
                ('huduu_count', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('status', models.CharField(default=saleor.unurshop.package.PackageStatus, max_length=32)),
                ('upostPK', models.CharField(blank=True, max_length=32, null=True)),
                ('net_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('gross_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('width', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('length', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency', models.CharField(default='GBP', max_length=3)),
                ('total_gross_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gaduur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packages', to='package.gaduurpackage')),
                ('sender_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='account.address')),
                ('shipping_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='account.address')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PackageLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('name', models.CharField(max_length=255)),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('currency', models.CharField(default='GBP', max_length=3)),
                ('unit_price_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('order_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='order.orderline')),
                ('package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lines', to='package.package')),
            ],
        ),
    ]
