# Generated by Django 3.1 on 2020-09-08 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0003_auto_20200828_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gaduurpackage',
            name='shipping_type',
            field=models.TextField(blank=True, max_length=10, null=True),
        ),
    ]
