# Generated by Django 3.1 on 2020-09-14 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0004_auto_20200908_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='status',
            field=models.CharField(default='draft', max_length=32),
        ),
    ]
