# Generated by Django 3.1 on 2020-09-16 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0006_auto_20200916_1440'),
    ]

    operations = [
        migrations.RenameField(
            model_name='packageline',
            old_name='fulfilmentline',
            new_name='fulfillmentline',
        ),
    ]
