# Generated by Django 3.1 on 2020-09-18 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0007_auto_20200916_1452'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='total_gross_amount',
        ),
        migrations.AddField(
            model_name='package',
            name='perkg_amount',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='gaduurpackage',
            name='actual_weight',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='gaduurpackage',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='gaduurpackage',
            name='total_cost',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='gaduurpackage',
            name='total_paid_amount',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='gaduurpackage',
            name='total_weight',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='gross_weight',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='length',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='net_weight',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='width',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='packageline',
            name='unit_price_amount',
            field=models.DecimalField(decimal_places=3, max_digits=12),
        ),
    ]
