# Generated by Django 3.1 on 2020-09-21 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0009_package_net_or_gross'),
    ]

    operations = [
        migrations.AddField(
            model_name='gaduurpackage',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('draft', 'Draft'), ('shipping', 'Shipping'), ('inmongolia', 'In Mongolia'), ('received', 'Received'), ('delayed', 'Delayed'), ('canceled', 'Canceled')], default='new', max_length=32),
        ),
        migrations.AlterField(
            model_name='package',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('draft', 'Draft'), ('shipping', 'Shipping'), ('inmongolia', 'In Mongolia'), ('received', 'Received'), ('delayed', 'Delayed'), ('canceled', 'Canceled')], default='draft', max_length=32),
        ),
    ]
