# Generated by Django 3.1 on 2020-11-10 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0011_package_package_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='gaduurpackage',
            name='received_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
