# Generated by Django 3.1 on 2020-11-19 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0013_auto_20201116_0140'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gaduurpackage',
            old_name='actual_weight',
            new_name='gross_weight',
        ),
        migrations.RenameField(
            model_name='gaduurpackage',
            old_name='total_weight',
            new_name='net_weight',
        ),
    ]
