# Generated by Django 3.1 on 2020-11-29 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0100_auto_20201129_2303'),
        ('package', '0014_auto_20201120_0407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packageline',
            name='fulfillmentline',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.fulfillmentline'),
        ),
    ]
