# Generated by Django 3.1 on 2020-12-01 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0016_auto_20201129_2308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gaduurpackage',
            name='status',
        ),
        migrations.RemoveField(
            model_name='package',
            name='status',
        ),
        migrations.AddField(
            model_name='gaduurpackage',
            name='ustatus',
            field=models.CharField(choices=[('new', 'New'), ('draft', 'Draft'), ('atuk', 'UK Салбарт ирсэн'), ('shipping', 'Shipping'), ('inmongolia', 'In Mongolia'), ('received', 'Received'), ('delayed', 'Delayed'), ('canceled', 'Canceled')], default='new', max_length=32),
        ),
        migrations.AddField(
            model_name='package',
            name='ustatus',
            field=models.CharField(choices=[('new', 'New'), ('draft', 'Draft'), ('atuk', 'UK Салбарт ирсэн'), ('shipping', 'Shipping'), ('inmongolia', 'In Mongolia'), ('received', 'Received'), ('delayed', 'Delayed'), ('canceled', 'Canceled')], default='draft', max_length=32),
        ),
    ]
