# Generated by Django 3.1 on 2020-12-23 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0103_remove_fulfillmentline_package_line'),
        ('package', '0018_auto_20201212_0638'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='order_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='order.orderline'),
        ),
    ]
