# Generated by Django 3.0.6 on 2020-06-27 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unurshop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='autofill',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='has_shipping_tax',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='listSelection',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='open_graph',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='productSelection',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='shipment_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='shipping_fee_free',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='shipping_fee_yaraltai',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='shipping_per_product',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='xero_id',
            field=models.CharField(blank=True, default=0, max_length=100, null=True),
        ),
    ]
