# Generated by Django 3.0.6 on 2020-08-03 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unurshop', '0003_shop_shipping_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='shipment_fee',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='shipping_deliver_free',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='shipping_deliver_standart',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='shipping_deliver_yaraltai',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='shipping_fee_free',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='shipping_fee_yaraltai',
        ),
    ]
