# Generated by Django 3.1 on 2020-08-16 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unurshop', '0004_auto_20200803_1609'),
    ]

    operations = [
        migrations.CreateModel(
            name='GaduurPackage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publication_date', models.DateField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=False)),
                ('name', models.TextField(max_length=20, unique=True)),
                ('shipping_type', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
