# Generated by Django 3.0.8 on 2020-08-06 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0026_auto_20200709_1102'),
        ('checkout', '0026_auto_20200625_1902'),
    ]

    operations = [
    ]
