# Generated by Django 3.1 on 2020-09-17 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0029_auto_20200824_1354'),
        ('checkout', '0029_auto_20200904_0529'),
    ]

    operations = [
    ]
