# Generated by Django 3.0.8 on 2020-08-06 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0084_auto_20200625_1903'),
        ('order', '0086_auto_20200716_1226'),
    ]

    operations = [
    ]
