# Generated by Django 3.1 on 2020-08-18 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0087_merge_20200806_1910'),
        ('order', '0088_auto_20200812_1101'),
    ]

    operations = [
    ]
