# Generated by Django 3.1 on 2020-09-16 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0095_auto_20200916_1405'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderline',
            name='changed_date',
        ),
        migrations.RemoveField(
            model_name='orderline',
            name='soon_date',
        ),
        migrations.RemoveField(
            model_name='orderline',
            name='ushop_status',
        ),
        migrations.AddField(
            model_name='fulfillmentline',
            name='changed_date',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='fulfillmentline',
            name='soon_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fulfillmentline',
            name='ushop_status',
            field=models.CharField(choices=[('new', 'New'), ('atuk', 'Англид ирсэн'), ('shipping', 'Тээвэрт орсон'), ('atmgl', 'Монголд ирсэн'), ('received', 'Хэрэглэгч хүлээж авсан')], default='new', max_length=32),
        ),
    ]
