# Generated by Django 3.1 on 2020-09-17 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0096_auto_20200916_1437'),
        ('order', '0089_auto_20200902_1249'),
    ]

    operations = [
    ]
