# Generated by Django 3.1 on 2020-10-12 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0097_merge_20200917_1401'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fulfillment',
            name='ushop_status',
        ),
    ]
