# Generated by Django 3.1 on 2020-11-03 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0098_remove_fulfillment_ushop_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='fulfillment',
            name='ushop_status',
            field=models.CharField(choices=[('new', 'New'), ('atuk', 'Англид ирсэн'), ('shipping', 'Тээвэрт орсон'), ('atmgl', 'Монголд ирсэн'), ('received', 'Хэрэглэгч хүлээж авсан')], default='new', max_length=32),
        ),
    ]
