# Generated by Django 3.1 on 2020-11-29 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0099_fulfillment_ushop_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fulfillment',
            name='ushop_status',
            field=models.CharField(choices=[('new', 'New'), ('atuk', 'Англид ирсэн'), ('shipping', 'Тээвэрт орсон'), ('inmongolia', 'Монголд ирсэн'), ('received', 'Хэрэглэгч хүлээж авсан')], default='new', max_length=32),
        ),
        migrations.AlterField(
            model_name='fulfillmentline',
            name='ushop_status',
            field=models.CharField(choices=[('new', 'New'), ('atuk', 'Англид ирсэн'), ('shipping', 'Тээвэрт орсон'), ('inmongolia', 'Монголд ирсэн'), ('received', 'Хэрэглэгч хүлээж авсан')], default='new', max_length=32),
        ),
    ]
