# Generated by Django 3.1 on 2020-11-29 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0015_auto_20201129_2303'),
        ('order', '0100_auto_20201129_2303'),
    ]

    operations = [
        migrations.AddField(
            model_name='fulfillmentline',
            name='package_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packagelines', to='package.packageline'),
        ),
    ]
