# Generated by Django 3.1 on 2020-12-01 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0101_fulfillmentline_package_line'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fulfillment',
            name='ushop_status',
        ),
        migrations.RemoveField(
            model_name='fulfillmentline',
            name='ushop_status',
        ),
        migrations.AddField(
            model_name='fulfillment',
            name='ustatus',
            field=models.CharField(choices=[('new', 'New'), ('draft', 'Draft'), ('atuk', 'UK Салбарт ирсэн'), ('shipping', 'Shipping'), ('inmongolia', 'In Mongolia'), ('received', 'Received'), ('delayed', 'Delayed'), ('canceled', 'Canceled')], default='new', max_length=32),
        ),
        migrations.AddField(
            model_name='fulfillmentline',
            name='ustatus',
            field=models.CharField(choices=[('new', 'New'), ('draft', 'Draft'), ('atuk', 'UK Салбарт ирсэн'), ('shipping', 'Shipping'), ('inmongolia', 'In Mongolia'), ('received', 'Received'), ('delayed', 'Delayed'), ('canceled', 'Canceled')], default='new', max_length=32),
        ),
    ]
