# Generated by Django 3.1 on 2020-09-23 05:14

from django.db import migrations, models
import django.db.models.deletion
import draftjs_sanitizer
import saleor.core.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ushop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crawler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publication_date', models.DateField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=False)),
                ('url', models.URLField(unique=True)),
                ('completed', models.BooleanField(default=False)),
                ('crawled_at', models.DateTimeField(auto_now=True, null=True)),
                ('product_count', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('json_data', saleor.core.db.fields.SanitizedJSONField(blank=True, default=dict, sanitizer=draftjs_sanitizer.clean_draft_js)),
                ('json_data_backup', saleor.core.db.fields.SanitizedJSONField(blank=True, default=dict, sanitizer=draftjs_sanitizer.clean_draft_js)),
                ('listSelection', models.TextField(blank=True)),
                ('productSelection', models.TextField(blank=True)),
                ('shop', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='crawlers', to='ushop.shop')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
